### ISSUE TITLE
Disabling CiviCRM stylesheet will make the Credit Card Icons and CVV icon disappear 

### ISSUE THREAD

**Issue by agileware-dat** [christianwach/civicrm-admin-utilities#10]
Hello,

When I prevent the default CiviCRM stylesheet, the Credit card icons and cvv icon on a CiviCRM contribution page will be replaced by texts, for example, VISA, MASTER ..

Would you mind to have a look at this issue?

Regards,
Agileware
CIVICRM-1176

**Comment by christianwach** [comment]
@agileware-dat If you are *just* disabling the default CiviCRM stylesheet on public pages, then that's to be expected. The whole point of that setting is that you supply your own stylesheet instead.
