### ISSUE TITLE
Add/edit menu items

### ISSUE THREAD

**Issue by Upperholme** [christianwach/civicrm-admin-utilities#11]
Great tool. Many thanks for this. It makes using Civi with Wordpress so much better. a quick question. what's the simple way to add to/edit the items in the menu that this plugin creates? I'd like to add a few links to Mosaico pages.

**Comment by christianwach** [comment]
@Upperholme Wow, missed this one. Quick answer - yes, via the `civicrm_admin_utilities_menu_before` or `civicrm_admin_utilities_menu_after` actions. In your callback use something like the following:

```php
// Add menu item.
$wp_admin_bar->add_node( array(
	'id' => 'civicrm-admin-utils',
	'title' => __( 'Your Title', 'your-slug' ),
	'href' => 'your-URL',
) );
```
