### ISSUE TITLE
Remove large margin on top of the page in shoreditch

### ISSUE THREAD

**Issue by netzih** [christianwach/civicrm-admin-utilities#12]
Iv'e seen that this plugin can fix it but I'm not seeing how to do it.
I'm on the latest versions of CIVI, Wordpress, shoreditch and CAU.

Thank you

**Comment by christianwach** [comment]
@netzih Thanks for the report -- I haven't paid attention to Shoreditch for some time as it keeps moving the goalposts and I don't really want to support it in combination with the native CiviCRM menu, the KAM Extension, the new Keyboard Accessible Menu and/or any other possible combination of CiviCRM, CiviCRM Extensions and WordPress versions.

I've added a commit to this repo which should auto-load my Shoreditch-fixes regardless of whether the menu-fixes setting is enabled. I'll push that to the WordPress Plugin Directory in due course, but you're welcome to download the plugin from here in the meantime.
