### ISSUE TITLE
Glitchy experience with Mosaico send/schedule screen

### ISSUE THREAD

**Issue by themak1985** [christianwach/civicrm-admin-utilities#13]
We have Wordpress 5.2, Civi 5.13.4, CiviCRM Admin Utilities admin theme on, Mosaico without shoreditch, chrome. 

When CiviCRM Admin Utilities admin theme is on - on the schedule/send review screen - the send button is bouncing all around - you can eventually find the sweet spot to submit.

Example:
https://photos.app.goo.gl/JdNrRtT1QnZJLwyr9

**Comment by christianwach** [comment]
@themak1985 Thanks for the report - should be fixed in 0f19b7534239e96e66c2087e4393cdb8a6aefa31
