### ISSUE TITLE
Rebuilding menu on multisite 

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-admin-utilities#14]
Using the link provided to rebuild menu within CAU doesn't rebuild menu in multisite. 

I am trying to add in the icons for Civi; it is easy to see it isn't happening.

Is the best way to approach this is to rebuild in SQL? https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/#build-the-navigation-links-for-new-domain

**Comment by christianwach** [comment]
@andyburnsco CAU doesn't actually do any menu rebuilding - it merely provides a link to the CiviCRM mechanism for doing so. I'd recommend that you open an issue with CiviCRM Core.
