### ISSUE TITLE
admin theme is broken by civiCRM 5.27.0

### ISSUE THREAD

**Issue by aardgoose** [christianwach/civicrm-admin-utilities#18]
The admin theme uses civicrm/i/TreePlus.gif images etc, which civiCRM no longer supplies.

**Comment by christianwach** [comment]
@aardgoose Thanks for the heads-up.

**Comment by christianwach** [comment]
Not technically *broken*, just missing a few icons ;-) Anyway, fixed in badd89fde39e3dcf5ebbce642036a02e554771c2

**Comment by aardgoose** [comment]
Thanks.  A fast fix!

**Comment by christianwach** [comment]
"Papering over the cracks" might be a better description. Thanks again for alerting me.
