### ISSUE TITLE
CiviCRM Theme Changes in v 5.31-RC 

### ISSUE THREAD

**Issue by kcristiano** [christianwach/civicrm-admin-utilities#19]
Due to the theme changes in CiviCRM 5.31 (moving the theme to an extension)  Enabling any of the CAU theme options will have problems.

![image](https://user-images.githubusercontent.com/1892544/95865822-1879df00-0d35-11eb-8a5c-0cfb5e29192c.png)

The above is a common setup.

With that enabled on upgrade:

Fatal errors are thrown

```
thrown in /srv/www/buildkit/wpcvrc/web/wp-content/plugins/civicrm/civicrm/CRM/Core/Region.php on line 140
[12-Oct-2020 14:40:03 UTC] PHP Fatal error:  Uncaught CRM_Core_Exception: [0: Snippet type  is unrecognized

  thrown in /srv/www/buildkit/wpcvrc/web/wp-content/plugins/civicrm/civicrm/CRM/Core/Region.php on line 140

```

```
"Snippet type is unrecognized"
civicrm/civicrm/CRM/Core/Region.php:140: throw new CRM_Core_Exception(ts('Snippet type %1 is unrecognized',
```

Disabling the admin theme and menu fixes allows upgrade, allowing the nav stylesheet to load on the front end will allow contribution pages to load.

On a clean install errors do not manifest unless style related options are chosen

Reference:   https://lab.civicrm.org/dev/core/-/issues/2117 

Edit:   Further testing shows that

![image](https://user-images.githubusercontent.com/1892544/95866859-6e9b5200-0d36-11eb-884c-26740caaea42.png)

Has no ill effects.

The two options that cause fatal errors are:

![image](https://user-images.githubusercontent.com/1892544/95866907-81158b80-0d36-11eb-816c-275e8acc75a0.png)

![image](https://user-images.githubusercontent.com/1892544/95866935-8a9ef380-0d36-11eb-8c27-81c1227c2d6e.png)

I have not yet tested all options.

**Comment by christianwach** [comment]
@kcristiano Thanks. This should be fixed in 0.7.4+
