### ISSUE TITLE
Multisite domain not available

### ISSUE THREAD

**Issue by jbonlinea** [christianwach/civicrm-admin-utilities#20]
Hi @christianwach 

### Brief context

This might not be the best place to ask, but CAU is the only source of information I have to debug the issue I encounter.

My aim is to set a WP multisite with CiviCRM, that may fit a "multi-tenant" approach. I 've read and folowed few documentation and tutorials (see below*), yet I bumped into an issue, ant the only reliable clue I have comes from CAU.

### the issue and information I have

Whichever site of my network I'am, whether the main site or a sub-site, WP dashboard > Settings > CAU > Domain > CiviCRM Domain Information says `The current domain for this site is: "mySite" (ID: 1)`

Obviously, my expectation is different. As the documentation and tutorials I relied on are not really comprehensive, I've spend the day trying various settings combinations, and I also ended up up activating mulstiste in CiviCRM > administer > system settings > multisite settings, despite I haven't seen any mention of this setting anywhere (see below*).

Anyhow what I have now looks likes this : 
- I have, supposedly successfully,  created multiste domain with Civi multisite module and wp-cli ; code and result are just below.
- CAU retunrs that `The current domain organization for this site is: "myMainOrganisation" (ID: 1)`
- CAU returns `The current domain group for this site is: "myMainGroup" (ID: 4)` (this is the right group ID - I defined it in CiviCRM multisite settings)
- the right groups are indeed bound to the right organizations in CiviCRM > contact > manage group

```
user@server:~/sites/kwagga.fr$ wp-cli cv api MultisiteDomain.create debug=1 sequential=1 name="sub.domain.net" is_transactional=0 group_id="2" contact_id="6"
Array
(
    [is_error] => 0
    [version] => 3
    [count] => 1
    [id] => 2
    [values] => Array
        (
            [2] => Array
                (
                    [id] => 2
                )

        )

    [xdebug] => Array
        (
        )

)

```
Note that I did it twice, once for the main site and once for a subsite. 

In phpMyAdmin, table civicrm_domain I indeed have two domains, associated with the right contac_id
However, table civicrm_website is still empty ?!

### the main question (I suppose)

If I'm right, the question is thus, at least first how do I get CAU, and thus CiviCRM, to identify and take into account the different domains of my network ? ie. when the url I'm on is `domain.net/wp-admin/admin.php?page=CiviCRM` or `sub.domain.net/wp-admin/admin.php?page=CiviCRM`

Then there may be others questions, but they may solve themselves once the above one is sorted ! 

In the end, I'm stuck, ACU let me know where, but not why ?! it would be awesome if you have a clue ! 
Regards

---
 for the poserity and deeper understanding

### what have I done

 I followed the various documentation or tutorial [here](https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/), [here](https://wiki.civicrm.org/confluence/pages/viewpage.action?pageId=86213708), [here](https://github.com/eileenmcnaughton/org.civicrm.multisite), and [here](https://redmine.palantetech.coop/projects/commons/wiki/CiviCRM_multi-site_checklist), plus few others Stack Exchange threads.

So Basically, 
- installed wp, activated multisite and created a sub-site
- installed CiviCRM and admin utilities, and activated them network wide
- I have[ not  defined CiviCRM constants in wp-config.php
](https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/#wordpress-multisite)
- from the main site
  - installed CiviCRM, set the location and organisation name
  - installed CiviCRM multisite module and activated it
  - created two Groups
  - created one multisite domain (as describe above)
- from there on, 
  - check what was up, between every change, and debug with the info I have, mostly coming form CAU
   - activating CiviCRM multisite form CiviCRM > administer > settings > multi-site settings
   - created a second multisite domain 
   - commented out the lines  described [here](https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/#wordpress-multisite-using-subdomains), but without adding the details of the sites, as the documentation say that you don't need it if you use the multisite module
  - defining the CiviCRM constant in wp-config.php [as described here](https://docs.civicrm.org/sysadmin/en/latest/install/multi-site/#wordpress-multisite) for the sake of testing
  - combined several possibilities, with total fresh reinstall and try with other settings

**Comment by christianwach** [comment]
@jbonlinea Sorry to hear you are having difficulties with multiple domains. I know it doesn't help you immediately but I'll share the setup docs as soon as they're properly written. I'm going to close this as it's not really a CAU issue.
