### ISSUE TITLE
Differentation between primary and non-primary data

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-admin-utilities#26]
On the stock civi theme (Greenwich), the bold is used to differentiate between what is a primary email/phone/address vs. non-primary. 

However, CAU bolds all labels removing that differentiation. I do like the bold labels look so I wouldn't want to just remove that to achieve this: https://github.com/christianwach/civicrm-admin-utilities/blob/master/assets/css/civicrm-admin-utilities-admin.css#L5270

I took a look at what the Shoreditch theme is doing and they are staring the primary:
![Untitled](https://user-images.githubusercontent.com/18341942/141164336-dab72f3f-dfc4-43a8-9c98-50d3ed23e04d.png)

FWIW, Raiser's Edge NXT does the same star method.

**Comment by christianwach** [comment]
I'll look into it @andyburnsco - but since the primary email/phone/address is always at the top of the stack, I see this as an enhancement of only marginal utility.

**Comment by andyburnsco** [comment]
Good to know about the top of the stack functionality but that's not clear to end-users.

**Comment by christianwach** [comment]
Fixed in #27
