### ISSUE TITLE
Network admin settings "Domains" tab is limited to showing the first 25 domains

### ISSUE THREAD

**Issue by mwittmann** [christianwach/civicrm-admin-utilities#28]
The "Domains" tab under WP Network Admin Settings will only show the first 25 Civi domains. I noticed this because I now have 29 domains!

I think this is due to the default Civi API limit of 25 records for API calls. I did not dig into the code, but I briefly switched on `define('CIVICRM_DEBUG_LOG_QUERY', 1);` in my dev environment `wp-config.php` and saw `SELECT * FROM civicrm_domain LIMIT 0, 25` in the log file.

I guess a fancy solution would be to use paging, but a quick improvement, since it's not a data-heavy page, might be to just raise the limit to, say, 250... and add a note indicating `"Results are limited to the first 250 domains."`, or use `SELECT SQL_CALC_FOUND_ROWS ... FROM ... LIMIT 0, 250;` then `SELECT FOUND_ROWS();` to generate a message like `"Results are limited to the first 250 of NNN domains."`.

**Comment by christianwach** [comment]
@mwittmann Nice catch. Should be fixed in ded3ed44e80c19d77f49fb1219155383a62442e5

**Comment by mwittmann** [comment]
Tested this and confirmed that fixes it for me. Thanks!
