### ISSUE TITLE
CiviCRM Shortcodes not working on WPengine

### ISSUE THREAD

**Issue by R-Frost** [christianwach/civicrm-admin-utilities#3]
Hi

thanks for your work on this - I use it all the time..

I've got a question which is not so much about the plugin but I figured you might well know the answer...  Im toying with moving my organisations site  to WPengine - for all the reasons you hear about  - my trial so far has been great  BUT today I struck an issue with shortcodes.. when you put one in a post or  a page, the page wont display - its a 500

The help desk has been pretty good in trying things but in the end said they'd run out of ideas.. so I'm asking more in hope than expectation.. any ideas of what permissions or whatever I could tell them to try?

thank you for any suggestions

**Comment by christianwach** [comment]
Hi Robert, glad you like this plugin.

I've never used WPEngine, but there is quite a lot of information on this topic [on StackExchange](https://civicrm.stackexchange.com/search?q=wpengine). You're going to need to look at your server logs to find the reason for the 500 error and then see if it matches any of the issues raised.

Cheers, Christian

**Comment by R-Frost** [comment]
Hi Christian

Thanks for your reply..I'm a bit of a beginner at this ...is it possible to
work out what the URLs are that the shortcodes replace?

**Comment by christianwach** [comment]
@R-Frost I'm not sure what you mean by this. Seriously, I'd ask your question(s) on StackExchange - you're likely to get responses from people who have used (or are using) WPEngine and who may already have solved the problem you're facing.

Cheers, Christian
