### ISSUE TITLE
Custom Stylesheet in CiviCRM Admin setting not respected - still loads in admin

### ISSUE THREAD

**Issue by andyburnsco** [christianwach/civicrm-admin-utilities#30]
After many hours of debugging I'm at a loss on this one. I've deactivated all plugins minus CiviCRM 5.45.2 and CAU 0.9.1 and used default 2020 theme. WP 5.7.5 multisite.

The CiviCRM custom CSS file is loading in the admin while we have the setting checked in CAU to prevent this:

![image](https://user-images.githubusercontent.com/18341942/152464557-40854ef2-a9b3-4cf9-9695-4552d5c4cbf5.png)

Out of curiosity I've tested the 3 other CiviCRM stylesheet settings to see if they still take effect when checked and they do
![image](https://user-images.githubusercontent.com/18341942/152465618-f764ad8f-72ef-459e-8402-d5109d352e04.png)

The 2 settings I check are:

- CiviCRM Menu stylesheet
- Custom Stylesheet in CiviCRM Admin

IIRC in my upgrade steps this did not occur on 5.40.4 but started occurring on 5.41.2.

Thoughts? Will fund further investigation of issue and fix.

**Comment by christianwach** [comment]
@andyburnsco Thanks for raising the issue. You're right - it seems that CiviCRM has changed the way in which this works. I'll look into a fix for more recent versions of CiviCRM.

**Comment by christianwach** [comment]
Ah, here we go: change happened in https://github.com/civicrm/civicrm-core/pull/20278

**Comment by andyburnsco** [comment]
I've tested https://github.com/christianwach/civicrm-admin-utilities/commit/9e0214d9cc31d9bfca13dfa7d604ad5273fb982b and it works. Thank you!
