### ISSUE TITLE
Front end CiviCRM pages not working in 5.46.3 with Radstock theme enabled

### ISSUE THREAD

**Issue by devappsoftware** [christianwach/civicrm-admin-utilities#31]
Since the security update, and the Radstock theme enabled, the front end forms are not formatting properly and previously were. When the theme is turned off, the front end in Wordpress functions as expected.

Screen shots attached with radstock on and then off.

<img width="856" alt="radstock off" src="https://user-images.githubusercontent.com/13082954/160959323-31902e38-6ab6-4f34-a306-052b253f9a41.png">
<img width="1339" alt="radstock on" src="https://user-images.githubusercontent.com/13082954/160959325-21e38fae-d3fc-4708-860f-aa0535df84fd.png">
<img width="1424" alt="radstock on 2" src="https://user-images.githubusercontent.com/13082954/160959302-e7ec2e57-6cfa-483d-9936-8688dc640f2b.png">

**Comment by christianwach** [comment]
@adam-devapp Which version of CiviCRM? (There were security updates to 5.45.x, 5.46.x and 5.47.x)

Also, can you explain what I'm looking at here? The first screenshot (Radstock on) looks as I would expect it to. The second (Radstock off) likewise looks unstyled - which I would expect with no theme enabled. Not sure what the third screenshot depicts... is it the unstyled "Manage" menu?

**Comment by themak1985** [comment]
@adam-devapp were you able to resolve this?

**Comment by christianwach** [comment]
@adam-devapp Does [this answer](https://github.com/christianwach/civicrm-admin-utilities/issues/32#issuecomment-1102909490) also apply here?
