### ISSUE TITLE
CiviCRM Admin Utils, will reset the Backend Theme to "Automatic" if Radstock is NOT selected which causes the previous selected theme to be unset

### ISSUE THREAD

**Issue by agileware-justin** [christianwach/civicrm-admin-utilities#38]
CiviCRM Admin Utils, will reset the Backend Theme to "Automatic" if "Radstock" theme is NOT selected which causes the previously selected theme to be unset. Which is a bummer when using "The Island" theme as there is a noticeable difference.

Sorry, do not have a PR or fix - just reporting.

Agileware Ref: CIVICRM-2240

**Comment by agileware-justin** [comment]
I think these were the steps:

1. Install Island Theme, CiviCRM extension
2. This changes the CiviCRM backend theme to Island Theme. Check that this is the case and if not, set the backend theme to Island Theme
3. Go to the CiviCRM Admin Utils page, check that Radstock theme is not enabled. Click Update.
4. Check the CiviCRM backend theme again, now set to Automatic. Should remain Island Theme.

**Comment by christianwach** [comment]
Thanks @agileware-justin I'll look into it.

**Comment by agileware-justin** [comment]
Thanks very much @christianwach

**Comment by christianwach** [comment]
FYI @agileware-justin I also [opened an MR on The Island](https://lab.civicrm.org/extensions/theisland/-/merge_requests/11) to fix its bad behaviour when the Extension is enabled but it's not the the active back-end theme.

**Comment by agileware-justin** [comment]
Thanks again!
