### ISSUE TITLE
Setting defaults on install

### ISSUE THREAD

**Issue by kcristiano** [christianwach/civicrm-admin-utilities#4]
Currently upon install the plugin defaults to no options set.

This has the effect that the user must go to the admin page to restore the CiviCRM shortcode button to posts/pages as well as choose the new options.

I would like to add this plugin as part of a scripted install - a CiviCRM WP demo site.   For that use case (and many of our client setups as well) we would want to set the options on install, or via a script (wp cli or php).

From my perspective, prettifying, adding the menu item and having the modal on posts and page are sane defaults and could be set on install.    

What options currently exist to enable/script this or can we look at adding?

**Comment by christianwach** [comment]
@kcristiano Settings sensible defaults seems... sensible. Will alter plugin defaults for 0.3.1 and release later today.

**Comment by christianwach** [comment]
@kcristiano Let me know if 564d13f14ccbae50c725a7d0602165cfc658d28e works for you and I'll push to the WordPress Plugins Directory.

**Comment by kcristiano** [comment]
Perfect.  This way we set the defaults and users can tweak them as needed.  Thanks.

**Comment by christianwach** [comment]
Great. I've updated https://wordpress.org/plugins/civicrm-admin-utilities/ to 0.3.1. Dev is now at 0.3.2.
