### ISSUE TITLE
Dual Calendar Symbols

### ISSUE THREAD

**Issue by Nevadamtb** [christianwach/civicrm-admin-utilities#7]
Not sure this is a bug but in the Civicrm date pickers I get both the cal.gif and the fa icons. Love the new style additions. Thanks!

**Comment by christianwach** [comment]
@Nevadamtb Which version of CiviCRM are you using?

**Comment by Nevadamtb** [comment]
5.7.2

**Comment by Nevadamtb** [comment]
It was a plugin. I had installed Mosaico (testing) which needs Shoreditch.

**Comment by christianwach** [comment]
Ah, I see, the `cal.gif` file was removed in [this PR](https://github.com/civicrm/civicrm-core/pull/13003)

**Comment by Nevadamtb** [comment]
So now I just have the cal.gif not the fa-calendar.

**Comment by christianwach** [comment]
Oh dear, this looks like it's going to be a bit complicated... this plugin may need a separate stylesheet for pre-5.7.2 and post-5.7.2. FWIW, I can see a similarly confusing issue with today's release of CiviCRM 5.8. For now, I'm just going to remove the `cal.gif` icon for the time being - it's fugly and doesn't really help anyone.

Annoyingly, the new CiviCRM template now contains the glyph, but for me, it's broken. Moreover, the `::placeholder` pseudo-element [doesn't support](https://css-tricks.com/almanac/selectors/p/placeholder/#article-header-id-4) `display: none;` so I can't hide it easily either. Time to open an issue in core methinks.

**Comment by christianwach** [comment]
@Nevadamtb Latest commit to this repo removes the icon in pre-5.8 and supports FontAwesome when it's available. Better than having both and better than having an unidentifiable square glyph.

Thanks for reporting this.
